language: python

sudo: required

dist: xenial

python:
  - "3.4"
  - "3.5"
  - "3.6"
  #- "3.7"

install:
   - pip install tox-travis

script:
  - tox

#deploy:
  # https://docs.travis-ci.com/user/deployment/pypi/
  #- provider: pypi
  #  user: fucm
  #  password:
  #    secure: yourencryptedpwhere
  #  distributions: "sdist bdist_wheel"
  #  skip_existing: true
  #  on:
  #    tags: true
